

/*credit_bank*/
INSERT INTO `credit_card`.`credit_bank` (`name`, `ext_keyword`, `online`, `email`, `status`, `update_date`, `create_date`, `code`, `version`, `short_name`, `user_id`, `repayment_cycle`, `interest_free_period`) VALUES ('中国农业银行', 'ABC，农业', '1', '1', '1', NULL, NULL, 'ABC', NULL, '农银', NULL, '25', '56');
INSERT INTO `credit_card`.`credit_bank` (`name`, `ext_keyword`, `online`, `email`, `status`, `update_date`, `create_date`, `code`, `version`, `short_name`, `user_id`, `repayment_cycle`, `interest_free_period`) VALUES ('交通银行', 'BCM，交通', '1', '1', '1', NULL, NULL, 'BCM', NULL, '交银', NULL, '25', '56');
INSERT INTO `credit_card`.`credit_bank` (`name`, `ext_keyword`, `online`, `email`, `status`, `update_date`, `create_date`, `code`, `version`, `short_name`, `user_id`, `repayment_cycle`, `interest_free_period`) VALUES ('北京银行', 'BOB，北京', '1', '1', '1', NULL, NULL, 'BOB', NULL, '北京', NULL, '20', '50');
INSERT INTO `credit_card`.`credit_bank` (`name`, `ext_keyword`, `online`, `email`, `status`, `update_date`, `create_date`, `code`, `version`, `short_name`, `user_id`, `repayment_cycle`, `interest_free_period`) VALUES ('中国银行', 'BOC', '1', '1', '1', NULL, NULL, 'BOC', NULL, '中国', NULL, '20', '50');
INSERT INTO `credit_card`.`credit_bank` (`name`, `ext_keyword`, `online`, `email`, `status`, `update_date`, `create_date`, `code`, `version`, `short_name`, `user_id`, `repayment_cycle`, `interest_free_period`) VALUES ('中国建设银行', 'CCB，建设', '1', '1', '1', NULL, NULL, 'CCB', NULL, '建行', NULL, '0', '50');
INSERT INTO `credit_card`.`credit_bank` (`name`, `ext_keyword`, `online`, `email`, `status`, `update_date`, `create_date`, `code`, `version`, `short_name`, `user_id`, `repayment_cycle`, `interest_free_period`) VALUES ('光大银行', 'CEB，光大', '1', '1', '1', NULL, NULL, 'CEB', NULL, '光大', NULL, '19', '50');
INSERT INTO `credit_card`.`credit_bank` (`name`, `ext_keyword`, `online`, `email`, `status`, `update_date`, `create_date`, `code`, `version`, `short_name`, `user_id`, `repayment_cycle`, `interest_free_period`) VALUES ('兴业银行', 'CIB，兴业', '1', '1', '1', NULL, NULL, 'CIB', NULL, '兴业', NULL, '20', '50');
INSERT INTO `credit_card`.`credit_bank` (`name`, `ext_keyword`, `online`, `email`, `status`, `update_date`, `create_date`, `code`, `version`, `short_name`, `user_id`, `repayment_cycle`, `interest_free_period`) VALUES ('中信银行', 'CITIC，中信', '1', '1', '1', NULL, NULL, 'CITIC', NULL, '中信', NULL, '19', '50');
INSERT INTO `credit_card`.`credit_bank` (`name`, `ext_keyword`, `online`, `email`, `status`, `update_date`, `create_date`, `code`, `version`, `short_name`, `user_id`, `repayment_cycle`, `interest_free_period`) VALUES ('招商银行', 'CMB，招商，信用管家消费提醒', '1', '1', '1', NULL, NULL, 'CMB', NULL, '招商', NULL, '0', '50');
INSERT INTO `credit_card`.`credit_bank` (`name`, `ext_keyword`, `online`, `email`, `status`, `update_date`, `create_date`, `code`, `version`, `short_name`, `user_id`, `repayment_cycle`, `interest_free_period`) VALUES ('中国民生银行', 'CMBC，民生', '1', '1', '1', NULL, NULL, 'CMBC', NULL, '民生', NULL, '20', '51');
INSERT INTO `credit_card`.`credit_bank` (`name`, `ext_keyword`, `online`, `email`, `status`, `update_date`, `create_date`, `code`, `version`, `short_name`, `user_id`, `repayment_cycle`, `interest_free_period`) VALUES ('广东发展银行', 'GDB，广发', '1', '1', '1', NULL, NULL, 'GDB', NULL, '广发', NULL, '23', '56');
INSERT INTO `credit_card`.`credit_bank` (`name`, `ext_keyword`, `online`, `email`, `status`, `update_date`, `create_date`, `code`, `version`, `short_name`, `user_id`, `repayment_cycle`, `interest_free_period`) VALUES ('中国工商银行', 'ICBC，工商', '1', '1', '1', NULL, NULL, 'ICBC', NULL, '工商', NULL, '0', '56');
INSERT INTO `credit_card`.`credit_bank` (`name`, `ext_keyword`, `online`, `email`, `status`, `update_date`, `create_date`, `code`, `version`, `short_name`, `user_id`, `repayment_cycle`, `interest_free_period`) VALUES ('深圳发展银行', 'SDB', '1', '1', '1', NULL, NULL, 'SDB', NULL, '深发', NULL, '0', '50');
INSERT INTO `credit_card`.`credit_bank` (`name`, `ext_keyword`, `online`, `email`, `status`, `update_date`, `create_date`, `code`, `version`, `short_name`, `user_id`, `repayment_cycle`, `interest_free_period`) VALUES ('上海浦东发展银行', 'SPDB，浦发', '1', '1', '1', NULL, NULL, 'SPDB', NULL, '浦发', NULL, '20', '50');
INSERT INTO `credit_card`.`credit_bank` (`name`, `ext_keyword`, `online`, `email`, `status`, `update_date`, `create_date`, `code`, `version`, `short_name`, `user_id`, `repayment_cycle`, `interest_free_period`) VALUES ('平安银行', 'PAB，平安', '1', '1', '1', NULL, NULL, 'PAB', NULL, '平安', NULL, '18', '50');
INSERT INTO `credit_card`.`credit_bank` (`name`, `ext_keyword`, `online`, `email`, `status`, `update_date`, `create_date`, `code`, `version`, `short_name`, `user_id`, `repayment_cycle`, `interest_free_period`) VALUES ('邮储银行', 'PSBC，邮储', '1', '1', '1', NULL, NULL, 'PSBC', NULL, '邮储', NULL, '20', '50');
INSERT INTO `credit_card`.`credit_bank` (`name`, `ext_keyword`, `online`, `email`, `status`, `update_date`, `create_date`, `code`, `version`, `short_name`, `user_id`, `repayment_cycle`, `interest_free_period`) VALUES ('浙商银行', '浙商', '1', '1', '1', NULL, NULL, 'CZB', NULL, '浙商', NULL, '25', '56');
INSERT INTO `credit_card`.`credit_bank` (`name`, `ext_keyword`, `online`, `email`, `status`, `update_date`, `create_date`, `code`, `version`, `short_name`, `user_id`, `repayment_cycle`, `interest_free_period`) VALUES ('华夏银行', '华夏', '1', '1', '1', NULL, NULL, 'HXB', NULL, '华夏', NULL, '20', '51');
INSERT INTO `credit_card`.`credit_bank` (`name`, `ext_keyword`, `online`, `email`, `status`, `update_date`, `create_date`, `code`, `version`, `short_name`, `user_id`, `repayment_cycle`, `interest_free_period`) VALUES ('包商银行', '包商', '1', '1', '1', NULL, NULL, 'BSB', NULL, '包商', NULL, '20', '56');
INSERT INTO `credit_card`.`credit_bank` (`name`, `ext_keyword`, `online`, `email`, `status`, `update_date`, `create_date`, `code`, `version`, `short_name`, `user_id`, `repayment_cycle`, `interest_free_period`) VALUES ('花旗银行', '花旗', '0', '0', '0', NULL, NULL, 'HQ', NULL, '花旗', NULL, '20', '50');
INSERT INTO `credit_card`.`credit_bank` (`name`, `ext_keyword`, `online`, `email`, `status`, `update_date`, `create_date`, `code`, `version`, `short_name`, `user_id`, `repayment_cycle`, `interest_free_period`) VALUES ('上海银行', '上海', '0', '0', '0', NULL, NULL, 'SH', NULL, '上海', NULL, '0', '56');
/*credit_cardtype*/
INSERT INTO `credit_card`.`credit_cardtype` (`bank_id`, `name`, `code`, `status`, `update_date`, `create_date`) VALUES ('34', '中信银行标准卡', 'CITIC_STANDARD', '1', NULL, NULL);
INSERT INTO `credit_card`.`credit_cardtype` (`bank_id`, `name`, `code`, `status`, `update_date`, `create_date`) VALUES ('35', '招商银行YOUNG卡', 'CMB_YOUNG', '1', NULL, NULL);
INSERT INTO `credit_card`.`credit_cardtype` (`bank_id`, `name`, `code`, `status`, `update_date`, `create_date`) VALUES ('35', '招商银行银联单币卡', 'CMB_UNIONPAY', '1', NULL, NULL);
INSERT INTO `credit_card`.`credit_cardtype` (`bank_id`, `name`, `code`, `status`, `update_date`, `create_date`) VALUES ('32', '光大信用卡PDF', 'CEB_DEFAULT', '1', NULL, NULL);
INSERT INTO `credit_card`.`credit_cardtype` (`bank_id`, `name`, `code`, `status`, `update_date`, `create_date`) VALUES ('27', '农业银行信用卡', 'ABC_DEFAULT', '1', NULL, NULL);
INSERT INTO `credit_card`.`credit_cardtype` (`bank_id`, `name`, `code`, `status`, `update_date`, `create_date`) VALUES ('43', '浙商银行信用卡', 'CZB_DEFAULT', '1', NULL, NULL);
INSERT INTO `credit_card`.`credit_cardtype` (`bank_id`, `name`, `code`, `status`, `update_date`, `create_date`) VALUES ( '29', '北京银行信用卡', 'BOB_DEFAULT', '1', NULL, NULL);
INSERT INTO `credit_card`.`credit_cardtype` (`bank_id`, `name`, `code`, `status`, `update_date`, `create_date`) VALUES ( '37', '广发银行信用卡', 'GDB_DEFAULT', '1', NULL, NULL);
INSERT INTO `credit_card`.`credit_cardtype` (`bank_id`, `name`, `code`, `status`, `update_date`, `create_date`) VALUES ( '45', '包商银行信用卡', 'BSB_DEFAULT', '1', NULL, NULL);
INSERT INTO `credit_card`.`credit_cardtype` (`bank_id`, `name`, `code`, `status`, `update_date`, `create_date`) VALUES ( '28', '交通银行信用卡', 'BCM_DEFAULT', '1', NULL, NULL);
INSERT INTO `credit_card`.`credit_cardtype` (`bank_id`, `name`, `code`, `status`, `update_date`, `create_date`) VALUES ( '33', '兴业银行信用卡', 'CIB_DEFAULT', '1', NULL, NULL);
INSERT INTO `credit_card`.`credit_cardtype` (`bank_id`, `name`, `code`, `status`, `update_date`, `create_date`) VALUES ( '32', '光大信用卡金卡', 'CEB_GOLD', '1', NULL, NULL);
INSERT INTO `credit_card`.`credit_cardtype` (`bank_id`, `name`, `code`, `status`, `update_date`, `create_date`) VALUES ( '31', '建行龙卡', 'CCB_LK', '1', NULL, NULL);
INSERT INTO `credit_card`.`credit_cardtype` (`bank_id`, `name`, `code`, `status`, `update_date`, `create_date`) VALUES ( '38', '工商银行牡丹卡', 'ICBC_MDC', '1', NULL, NULL);
INSERT INTO `credit_card`.`credit_cardtype` (`bank_id`, `name`, `code`, `status`, `update_date`, `create_date`) VALUES ( '40', '浦发银行信用卡', 'SPDB', '1', NULL, NULL);
INSERT INTO `credit_card`.`credit_cardtype` (`bank_id`, `name`, `code`, `status`, `update_date`, `create_date`) VALUES ( '42', '邮政储蓄银行信用卡', 'PSBC_DEFAULT', '1', NULL, NULL);
INSERT INTO `credit_card`.`credit_cardtype` (`bank_id`, `name`, `code`, `status`, `update_date`, `create_date`) VALUES ( '36', '民生银行信用卡', 'CMBC_DEFAULT', '1', NULL, NULL);
INSERT INTO `credit_card`.`credit_cardtype` (`bank_id`, `name`, `code`, `status`, `update_date`, `create_date`) VALUES ( '41', '平安银行信用卡', 'PAB_DEFAULT', '1', NULL, NULL);
INSERT INTO `credit_card`.`credit_cardtype` (`bank_id`, `name`, `code`, `status`, `update_date`, `create_date`) VALUES ( '35', '招商银行信用卡详细完整版', 'CMB_COMPLETE', '1', NULL, NULL);
INSERT INTO `credit_card`.`credit_cardtype` (`bank_id`, `name`, `code`, `status`, `update_date`, `create_date`) VALUES ( '35', '招商银行信用卡明细', 'CMP_DETAIL', '1', NULL, NULL);
